## Redirect to home for the root index.html
[[redirects]]
from = "/index.html"
to = "/home/"
status = 301

[[redirects]]
from = "/"
to = "/home/"
status = 301

## temporarily under construction
[[redirects]]
from = "/404.html"
to = "/home/"
status = 302
