[[redirects]]
from = "/index.html"
to = "/home/"
status = 301

[[redirects]]
from = "/"
to = "/home/"
status = 301

[[redirects]]
from = "/404.html"
to = "/home/"
status = 302

from = "/downloads/"
to = "/extras?cat=downloads"
status = 301

from = "/favicon.ico"
to = "/images/logos/rubberocket_icon.ico"
status = 301