## There's not really much use for the index file
[[redirects]]
from = "/index.html"
to = "/home/"
status = 301

[[redirects]]
from = "/"
to = "/home/"
status = 301

## Categories
[[redirects]]
from = "/toons/"
to = "/videos/?category=cartoons"
status = 301

# I don't like that netlify subdomain.
[[redirects]]
from = "https://rubberocket.netlify.app/*"
to = "https://rubberocket.com/*"
status = 301
